<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjbT4Nk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjbT4Nk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZjbT4Nk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZjbT4Nk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZjbT4Nk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZjbT4Nk',
    'container.build_id' => 'a7ca98d3',
    'container.build_time' => 1573052013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjbT4Nk');
